- name: APT Update & APT Upgrade
  hosts: 10.5.150.15
  become: true

  tasks:
    - name: Update APT Cache & Upgrade ALL packages
      register: updatesys
      apt:
        name: "*"
        state: latest
        update_cache: yes
